export const accountConstants = {
    CONNECT_SUCCESS: 'CONNECT_SUCCESS',
    CONNECT_FAILURE: 'CONNECT_ERROR',
    CONNECT_REQUEST: 'CONNECT_FAILURE',

    ACCOUNT_SUCCESS: 'ACCOUNT_SUCCESS',
    ACCOUNT_FAILURE: 'ACCOUNT_ERROR',
    ACCOUNT_REQUEST: 'ACCOUNT_FAILURE',
};