export const bankConstants = {
    BANK_SUCCESS: 'BANK_SUCCESS',
    BANK_FAILURE: 'BANK_ERROR',
    BANK_REQUEST: 'BANK_FAILURE',

    CONNECT_SUCCESS: 'CONNECT_SUCCESS',
    CONNECT_FAILURE: 'CONNECT_ERROR',
    CONNECT_REQUEST: 'CONNECT_FAILURE',
};