export const billConstants = {
    BILL_SUCCESS: 'BILL_SUCCESS',
    BILL_FAILURE: 'BILL_ERROR',
    BILL_REQUEST: 'BILL_FAILURE',

    TYPE_SUCCESS: 'BILL_TYPE_SUCCESS',
    TYPE_FAILURE: 'BILL_TYPE_ERROR',
    TYPE_REQUEST: 'BILL_TYPE_FAILURE',
};