export const servicesConstants = {
    TRANSFER_SUCCESS: 'TRANSFER_SUCCESS',
    TRANSFER_FAILURE: 'TRANSFER_ERROR',
    TRANSFER_REQUEST: 'TRANSFER_FAILURE',

    MOBILE_SUCCESS: 'PAY_MOBILE_SUCCESS',
    MOBILE_FAILURE: 'PAY_MOBILE_ERROR',
    MOBILE_REQUEST: 'PAY_MOBILE_FAILURE',

    DEPOSIT_SUCCESS: 'DEPOSIT_SUCCESS',
    DEPOSIT_FAILURE: 'DEPOSIT_ERROR',
    DEPOSIT_REQUEST: 'DEPOSIT_FAILURE',

    PAY_SUCCESS: 'PAY_BILL_SUCCESS',
    PAY_FAILURE: 'PAY_BILL_ERROR',
    PAY_REQUEST: 'PAY_BILL_FAILURE',

};