export const servicesConstants = {
    TRANSFER_SUCCESS: 'TRANSFER_SUCCESS',
    TRANSFER_FAILURE: 'TRANSFER_ERROR',
    TRANSFER_REQUEST: 'TRANSFER_FAILURE',

    MOBILE_SUCCESS: 'PAY_MOBILE_SUCCESS',
    MOBILE_FAILURE: 'PAY_MOBILE_ERROR',
    MOBILE_REQUEST: 'PAY_MOBILE_FAILURE',
};