export const servicesConstants = {
    TRANSFER_SUCCESS: 'TRANSFER_SUCCESS',
    TRANSFER_FAILURE: 'TRANSFER_ERROR',
    TRANSFER_REQUEST: 'TRANSFER_FAILURE',

    TRANSACT_SUCCESS: 'TRANSACT_SUCCESS',
    TRANSACT_FAILURE: 'TRANSACT_ERROR',
    TRANSACT_REQUEST: 'TRANSACT_FAILURE',
};