"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("react");
const react_router_dom_1 = require("react-router-dom");
class Footer extends React.Component {
    render() {
        return React.createElement("footer", { class: "footer", id: "contact" },
            React.createElement("div", { class: "top-footer" },
                React.createElement("div", { class: "container" },
                    React.createElement("div", { class: "row" },
                        React.createElement("div", { class: "col-sm-4 col-md-2" },
                            React.createElement("h4", null, "Our Company"),
                            React.createElement("div", { class: "menu" },
                                React.createElement("ul", null,
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/" }, "Home")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/customer" }, "Customer")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/services" }, "Services")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/guide" }, "Guide")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/contact" }, "Contact"))))),
                        React.createElement("div", { class: "col-sm-4 col-md-2" },
                            React.createElement("h4", null, "Our services"),
                            React.createElement("div", { class: "menu" },
                                React.createElement("ul", null,
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/customer/services/transfer" }, "Transfer")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/customer/services/deposit" }, "Deposit")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/customer/services/pay" }, "Pay Bill")),
                                    React.createElement("li", null,
                                        React.createElement(react_router_dom_1.Link, { to: "/customer/services/mobile" }, "Mobile Pay"))))),
                        React.createElement("div", { class: "col-sm-4 col-md-3" },
                            React.createElement("h4", null, "Contact Us "),
                            React.createElement("div", { class: "contacts" },
                                React.createElement("div", null,
                                    React.createElement("span", null, "thanhtung29497@gmail.com")),
                                React.createElement("div", null,
                                    React.createElement("span", null, "012345678910")),
                                React.createElement("div", null,
                                    React.createElement("span", null, "Hanoi, Vietnam")),
                                React.createElement("div", null,
                                    React.createElement("span", null, "Mon-Sat 08am \u21FE 05pm"))),
                            React.createElement("div", { class: "social-footer" },
                                React.createElement("ul", null,
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "https://fb.com/thanhtung29497", target: "_blank" },
                                            React.createElement("i", { class: "fab fa-facebook" }))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "https://twitter.com/ecommer38342799", target: "_blank" },
                                            React.createElement("i", { class: "fab fa-twitter" }))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "https://www.youtube.com/channel/UC7PbNnYZjgNfs7if36syXpQ", target: "_blank" },
                                            React.createElement("i", { class: "fab fa-youtube" }))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "https://github.com/thanhtung29497", target: "_blank" },
                                            React.createElement("i", { class: "fab fa-github" })))))),
                        React.createElement("div", { class: "col-sm-12 col-md-5" },
                            React.createElement("div", { class: "facts-footer" },
                                React.createElement("div", null,
                                    React.createElement("h5", null, "13"),
                                    React.createElement("span", null, "Supported bank")),
                                React.createElement("div", null,
                                    React.createElement("h5", null, "5"),
                                    React.createElement("span", null, "Supported telecom company")),
                                React.createElement("div", null,
                                    React.createElement("h5", null, "100K"),
                                    React.createElement("span", null, "active accounts"))),
                            React.createElement("hr", null))))),
            React.createElement("div", { class: "bottom-footer" },
                React.createElement("div", { class: "container" },
                    React.createElement("div", { class: "row" },
                        React.createElement("div", { class: "col-xs-12" },
                            React.createElement("p", { class: "text-center" },
                                "Copyright \u00A9 2019 E-Wallet All Rights Reserved | Created with Love by ",
                                React.createElement("a", { href: "https://github.com/thanhtung29497", target: "_blank" }, "Tung")))))));
    }
}
exports.default = Footer;
